---
title: "HW5"
author: "Pablo Maldonado"
date: "12/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(broom)
library(purrr)
library(ggplot2)
library(forcats)
library(ggthemes)
library(lubridate)
library(plotly)
```

# Load the data
```{r}

homicides <- read.csv("data/homicide-data.csv")

homicides <- homicides %>%
  unite("city_name", city:state, sep = ", ")
```


# Just show baltimore
```{r}
baltimore <- homicides %>% 
  filter(city_name == "Baltimore, MD")


baltimore %>%
  filter(grepl("GREY", victim_last))
```

# Group by month and year
```{r}
#
baltimore_mutate_date <- baltimore %>%
  mutate(reported_date = ymd(reported_date)) %>%
  mutate(year = year(reported_date)) %>%
  mutate(month = month(reported_date)) %>%
  mutate(day = day(reported_date)) %>%
  group_by(year, month) %>%
  count() 

baltimore_mutate_date <- baltimore_mutate_date %>%
  mutate(date = paste(year, month,"15", sep = "-")) %>%
  mutate(date = ymd(date))


baltimore_mutate_date
```


# separate by cold or warm years
```{r}
baltimore_summary <- baltimore_mutate_date %>%
  mutate(winter = month %in% c(11, 12, 1:4)) %>%
  mutate(summer = month %in% c(5:10))

```

# plotting 
```{r, fig.width= 3.5, fig.height=.95}
baltimore_summary_graph <- baltimore_summary %>%
  ggplot(aes(x = date, y = n)) + 
  geom_col(aes(fill = winter)) +
  geom_vline(xintercept = ymd("2015-04-15"), color ="red", linetype = 2, size = 1.5) +
  annotate("text", x = ymd("2014-10-15"), y = 42, label = "Arrest of", color = "white") +
  annotate("text", x = ymd("2014-0-15"), y = 35, label = "Freddie Gray", color = "white") +
  theme_dark() +
  ggtitle("Homicides in Baltimore, MD") +
  labs(y = "Monthly homicides", x = "Date") +
  theme(legend.position = "bottom")

baltimore_summary_graph
```